import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '../../components/Navbar';
import Footer from '../../components/Footer';
import Description from '../../components/Description';
import WhyUsDescription from "../../components/WhyUsDescription";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="main-container">
          <Navbar /> {/* use Navbar component */}
          {children}

          <Footer /> {/* use Footer component */}
        </div>
      </body>
    </html>
  );
}